name: Flyway Migration
description: Migrate database in Github Action
branding:
  color: red
  icon: database
inputs:
  url:
    description: The jdbc url to use to connect to the database
    required: true
  user:
    description: The user to use to connect to the database
    required: false
  password:
    description: The password to use to connect to the database
    required: false
  locations:
    description: Comma-separated list of locations to scan recursively for migrations
    required: true
    default: filesystem:./sql
  schemas:
    description: The schema name you are migrating in the dadtabase
    required: false
    default: public
  initSql:
    description: The SQL statements to run to initialize a new database connection immediately after opening it
    required: false
  webuser:
    description: just in case there is a user that is not the one running these migrations
    required: false    
runs:
  using: docker
  image: docker://flyway/flyway:11
  env:
    FLYWAY_URL: ${{ inputs.url }}
    FLYWAY_USER: ${{ inputs.user }}
    FLYWAY_SCHEMAS: ${{ inputs.schemas }}
    FLYWAY_PASSWORD: ${{ inputs.password }}
    FLYWAY_LOCATIONS: ${{ inputs.locations }}
    FLYWAY_INIT_SQL: ${{ inputs.initSql }}
    FLYWAY_PLACEHOLDERS_WEBUSER: {{inputs.webuser}}
  args:
    - migrate
    
