name: ci
on:
  push:
    branches: 
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: local
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: nathansutton/flyway-action@v9
        with:
          url: jdbc:postgresql://postgres:5432/postgres
          user: local
          password: password
          locations: filesystem:./sql/schema1/
          schemas: schema1
      - uses: nathansutton/flyway-action@v9
        with:
          url: jdbc:postgresql://postgres:5432/postgres
          user: local
          password: password
          locations: filesystem:./sql/schema1/
          schemas: schema1
